// Export all endpoints
export * from "./auth.endpoint";
export * from "./user.endpoint";
export * from "./loan.endpoint";
export * from "./payment.endpoint";
export * from "./consultancy.endpoint";
export * from "./report.endpoint";
export * from "./sms.endpoint";
export * from "./notification.endpoint";
